#ifndef __GRETA_H
#define __GRETA_H

#include "Riostream.h"
#include "Rtypes.h"

#include "TObject.h"
#include "TString.h"
#include "TVector3.h"
#include "TClass.h"
#include "TH1F.h"
#include "TGraph.h"
#include "SortingStructures.h"

#include <vector>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <arpa/inet.h>

#include "dptc.h"

#include "colors.h"

using std::vector;
using std::cout;  using std::endl;
using std::swap;

#define NUM_CHAN 40
#define MAXCRYSTALS 120

/* GRETA Data Structures */

struct routingHdr {
  uint8_t version;   /* protocol version */
  uint8_t flags;     /* for future use, e.g. debugging */
  uint8_t type;      /* [0..4] ge waveform, scalar digest */
  uint8_t subtype;   /* message sub-type, e.g. crystal ID for waveform messages */
  uint16_t length;   /* length of payload */
  uint16_t seqnum;   /* sequence number */
  int64_t timestamp; /* generated by trigger (10ns clock) */
  int64_t checksum;  /* integrity checksum */
};

struct gretaWaveformMsg {
  /* This is coming from the Google document: 
     Interface/Specifications: Filter Board to Forward Buffer
     Format taken on Nov. 15 / 2019  -  HLC                     */
  uint8_t  version;    /* protocol version = 0x1 for prototype waveform version */
  uint8_t  id;         /* crystal id */
  uint16_t tr_len;     /* trace length (in 2-byte words) */
  uint16_t trig_src;   /*info from trigger */
  uint16_t pad;        /* pad to 8-byte alignment */
  int64_t  timestamp;  /* timestamp of first sample */
  uint64_t pileup;           /* pileup flags for filter 1 */
  int16_t  hist_corr[2][2];  /* energy/time pairs of preceeding 2 events */
  int16_t  t0;           /* time offset for decomp (if available) */
  int16_t  sub_t0;       /* sub-tick time for decomp (if available) */
  int16_t  t_led_core;   /* time offset for core LED */
  int16_t  t_cfd_core;   /* time offset for core CFD */
  int16_t  t_led_first;  /* time offset for LED of first hit */
  int16_t  t_postpileup; /* time offset for post pileup */
  int16_t  t_ovfl;       /* time offset since last overflow */
  int16_t  t_rst;        /* time offset since last reset */
  int32_t  ener[NUM_CHAN];   /* energy given by filter 1 */
  uint16_t wfLength[NUM_CHAN];
  // int16_t  tr[NUM_CHAN][96];  /* waveforms */
};

struct intPt{
  int16_t ir, ip, iz, seg;
  float x, y, z, e;
  float dx, dy, dz, de;
};

struct intPtFit{
  int16_t fit_type;
  int16_t fit_flags;
  int16_t num_interactions;
  int16_t errorCode;
  float_t chisq;
  float_t norm_chisq;
  float_t fit_t0;
  uint32_t pad;
  // vector<intPt> intpts;
};

struct gretaIntPtMsg {
  uint8_t  version;    /* protocol version = 0x1 for prototype waveform version */
  int8_t  id;         /* crystal id */
  uint16_t trig_src;   /*info from trigger */
  int16_t  num_fits;
  uint16_t pad;        /* pad to 8-byte alignment */
  uint64_t basisHash;  /* a unique id tied to the basis */
  int64_t  timestamp;  /* timestamp of first sample */
  uint64_t pileup;           /* pileup flags for filter 1 */
  int16_t  t0;           /* time offset for decomp (if available) */
  int16_t  sub_t0;       /* sub-tick time for decomp (if available) */
  int16_t  hist_corr[2][2];  /* energy/time pairs of preceeding 2 events */
  int16_t  t_led_core;   /* time offset for core LED */
  int16_t  t_cfd_core;   /* time offset for core CFD */
  int16_t  t_led_first;  /* time offset for LED of first hit */
  int16_t  t_postpileup; /* time offset for post pileup */
  int16_t  t_ovfl;       /* time offset since last overflow */
  int16_t  t_rst;        /* time offset since last reset */
  int32_t  ener[NUM_CHAN];   /* energy given by filter 1 */
  // vector<intPtFit> intPtFits;
};

class g3CrystalEvent : public TObject {
 public:
  uint16_t rhSequence;
  int64_t  rhTS; /* generated by trigger (10ns clock) */
  uint8_t  rhSubType;
  uint8_t  version;    /* protocol version = 0x1 for prototype waveform version */
  uint8_t  id;         /* crystal id */
  uint16_t trLen;     /* trace length (in 2-byte words) */
  uint16_t trigSrc;   /*info from trigger */
  uint16_t pad;        /* pad to 8-byte alignment */
  int64_t   timestamp;  /* timestamp of first sample */
  uint64_t pileup;           /* pileup flags for filter 1 */
  uint16_t  hist_corr[2][2];  /* energy/time pairs of preceeding 2 events */
  int16_t  t0;           /* time offset for decomp (if available) */
  int16_t  subt0;       /* sub-tick time for decomp (if available) */
  int16_t  tLEDCore;   /* time offset for core LED */
  int16_t  tCFDCore;   /* time offset for core CFD */
  int16_t  tLEDFirst;  /* time offset for LED of first hit */
  int16_t  tPostpileup; /* time offset for post pileup */
  int16_t  tOvfl;       /* time offset since last overflow */
  int16_t  tRst;        /* time offset since last reset */
  int32_t  ener[NUM_CHAN];   /* energy given by filter 1 */
  vector<vector<int16_t>> tr;//[NUM_CHAN];
  //int16_t* trA[NUM_CHAN];
  //  int16_t  tr[NUM_CHAN][512];  /* waveforms */
  vector<Float_t>  ccE;
  vector<Float_t>  segE;
  vector<Int_t> segsHit;
  Int_t noNeighbors;

 public:
  g3CrystalEvent() { ; }
  ~g3CrystalEvent() { ; }
  void Clear();
  UInt_t segMult() { return segsHit.size(); }
  TGraph* GetSegTrace(Int_t seg);
  TGraph* GetFullTrace();
  
 private:
  ClassDef(g3CrystalEvent, 1);
};

class g3OUT : public TObject {
 public:
  vector<g3CrystalEvent> xtals;

 public:
  g3OUT() { ; }
  ~g3OUT() { ; }
  void Reset();
  UInt_t crystalMult();
  Float_t calorimeterE();

 private:
  ClassDef(g3OUT, 1);
};

class g2IntPts : public TObject {
 public:
  int16_t ir, ip, iz, seg;
  TVector3 xyzCrystal;
  TVector3 xyzLab;
  TVector3 xyzLabSeg;
  float e;
  float dx, dy, dz, de;
  int16_t fit_type;
  int16_t fit_flags;
  int16_t errorCode;
  float_t chisq;
  float_t fit_t0;

 public:
  g2IntPts() { ; }
  ~g2IntPts() { ; }
  void Reset();
  
 private:
  ClassDef(g2IntPts, 1);
};

class g2CrystalEvent : public TObject {
 public:
  uint16_t rhSequence;
  int64_t  rhTS; /* generated by trigger (10ns clock) */
  uint8_t  rhSubType;
  uint8_t  id;         /* crystal id */
  uint16_t trig_src;   /*info from trigger */
  int16_t  num_fits;
  int64_t  timestamp;  /* timestamp of first sample */
  Float_t  ener[NUM_CHAN];   /* energy given by filter 1 */
  uint64_t pileup;           /* pileup flags for filter 1 */
  int16_t  t0;           /* time offset for decomp (if available) */
  int16_t  sub_t0;       /* sub-tick time for decomp (if available) */
  int16_t  hist_corr[2][2];  /* energy/time pairs of preceeding 2 events */
  int16_t  t_led_core;   /* time offset for core LED */
  int16_t  t_cfd_core;   /* time offset for core CFD */
  int16_t  t_led_first;  /* time offset for LED of first hit */
  int16_t  t_postpileup; /* time offset for post pileup */
  int16_t  t_ovfl;       /* time offset since last overflow */
  int16_t  t_rst;        /* time offset since last reset */
  int16_t errorCode; /* error code from first fit */
  vector<g2IntPts> intPts;
  vector<int16_t> tr[NUM_CHAN];
  
 public:
  g2CrystalEvent() { ; }
  ~g2CrystalEvent() { ; }
  void Reset();
  TVector3 maxIntPtXYZLab();
  Double_t maxIntPtX();
  Double_t maxIntPtY();
  Double_t maxIntPtR();
  Double_t maxIntPtZ();
  Float_t gTheta();
  Float_t gPhi();
  UInt_t numIntPts();
  
 private:
  ClassDef(g2CrystalEvent, 1);
};

class g2OUT : public TObject {
 public:
  vector<g2CrystalEvent> xtals;

 public:
  g2OUT() { ; }
  ~g2OUT() { ; }
  void Reset();
  UInt_t crystalMult();
  
 private:
  ClassDef(g2OUT, 1);
};

/******** Rotation matrix for crystal to lab transformation ********/

class rotationMatrix : public TObject {
 
 public:
  Float_t crmat[30][4][4][4];
  
 public:
  rotationMatrix() { ; }
  rotationMatrix(TString file) { ReadMatrix(file); }
  ~rotationMatrix() { ; }
  Int_t ReadMatrix(TString file);
  TVector3 crys2Lab(Int_t crystalID, TVector3 xyz);
  
  ClassDef(rotationMatrix, 1);
};

class GRETA : public TObject {
 public:
  rotationMatrix rot;
  
  g3CrystalEvent g3X;
  unsigned char gBuf[32*32*1024];

  g2CrystalEvent g2X;
  g2IntPts g2Xip;
  
  g3OUT g3Out;
  g2OUT g2Out;

  uint64_t ng2;
  
  std::map<int, int> segMap;
  Float_t gain[121][40];
  Float_t offset[121][40];

  Float_t segCenter[2][3][36];

  Int_t doingACalibration;
  
  TH1F *ccSpec[121][4];
  TH1F *ccAll[4];
  TH1F *dT[121];
  TH1F *segSpec[121][36];
  
 public:
  GRETA() { ; }
  ~GRETA() { ; }
  void Initialize(controlVariables *ctrl);
  void ReadSegmentCenters(TString filename);
  void Reset();
  Int_t getMode3(FILE *inf, Int_t evtLength, Int_t subType, Int_t type);
  Int_t getMode2(FILE *inf, Int_t evtLength, Int_t subType);
  Int_t analyzeMode3(g3CrystalEvent *g3);
  uint64_t ntoh64(uint64_t input);
  uint64_t hton64(uint64_t input);
  void readGRETACalibration(TString filename);
  
 public:
  ClassDef(GRETA, 1);
};

#endif
